Comment :  on Tue Mar  7 12:59:23 CET 2017

diff --git a/installation/personal/settings/openbox/scripts/al-compositor b/installation/personal/settings/openbox/scripts/al-compositor
--- a/installation/personal/settings/openbox/scripts/al-compositor
+++ b/installation/personal/settings/openbox/scripts/al-compositor
@@ -1,5 +1,5 @@
 #!/bin/bash
-#    bl-compositor: an Openbox Pipe Menu for use with compton compositor
+#    al-compositor: an Openbox Pipe Menu for use with compton compositor
 #    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
 #    Copyright (C) 2013 Aleks-Daniel Jakimenko
 #    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
@@ -17,7 +17,7 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-HELP='    bl-compositor an Openbox Pipe Menu for use with compton compositor
+HELP='    al-compositor an Openbox Pipe Menu for use with compton compositor
     It should normally be called from an openbox menu.
 
 Options (usually passed from the menu):
@@ -29,7 +29,7 @@ Options (usually passed from the menu):
     --watch     restart the compositor whenever the config file is modified
     (--watch is useful for debugging)
 
-    If bl-compositor is called with no options (the usual method),
+    If al-compositor is called with no options (the usual method),
     it will output an xml openbox pipemenu for handling compositing.
 
 See ~/.config/compton.conf and "man compton" for configuration options.
@@ -47,10 +47,10 @@ done
 
 RESTART_ATTEMPTS=20 # times to try killall before reverting to -s KILL
 
-BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
+BL_COMMON_LIBDIR='/usr/lib/archlabs/common'
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to source al-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
@@ -83,12 +83,12 @@ if [[ $1 = '--edit' ]]; then # Edit compton settings
     if type geany >/dev/null;then
         geany "$HOME/.config/compton.conf"
     else
-        x-terminal-emulator -T 'edit compton.conf' -e nano "$HOME/.config/compton.conf"
+        termite -T 'edit compton.conf' -e nano "$HOME/.config/compton.conf"
     fi
 elif [[ $1 = '--start' ]]; then
     if ! pidof compton > /dev/null; then
         $EXECXCOMP
-        bl-tint2restart || true
+        al-tint2restart || true
     else
         echo "$0 --start: compton already running" >&2
     fi
diff --git a/installation/personal/settings/openbox/scripts/al-conky-pipemenu b/installation/personal/settings/openbox/scripts/al-conky-pipemenu
--- a/installation/personal/settings/openbox/scripts/al-conky-pipemenu
+++ b/installation/personal/settings/openbox/scripts/al-conky-pipemenu
@@ -15,7 +15,7 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-HELP='    bl-conky-pipemenu an Openbox Pipe Menu for use with conky
+HELP='    al-conky-pipemenu an Openbox Pipe Menu for use with conky
     It should normally be called from an openbox menu.
 
 Options:
@@ -44,12 +44,12 @@ CONKYDEFAULT="$HOME/.conkyrc"
 CONKYPATH="$HOME/.config/conky"
 CSESSIONFILE="$CONKYPATH/conky-sessionfile"
 SESSIONS="$CONKYPATH/saved-sessions"
-CZEN="bl-conkyzen"
+CZEN="al-conkyzen"
 CSESSION="al-conky-session"
 HELPFILE="/usr/share/archlabs/docs/helpfile-conkyzen.txt"
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo "Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo "Error: Failed to source al-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 if [ ! -e "$CSESSIONFILE" ] 2> /dev/null ; then
@@ -102,7 +102,7 @@ loadSavedsessionSubmenu(){
 }
 
 loadPinMenu(){
-    if type bl-conkypin &>/dev/null;then
+    if type al-conkypin &>/dev/null;then
         menuItem "Pin moveable Conkys" "al-conkypin"
         menuSeparator
     fi
diff --git a/installation/personal/settings/openbox/scripts/al-help-pipemenu b/installation/personal/settings/openbox/scripts/al-help-pipemenu
--- a/installation/personal/settings/openbox/scripts/al-help-pipemenu
+++ b/installation/personal/settings/openbox/scripts/al-help-pipemenu
@@ -1,5 +1,5 @@
 #!/bin/bash
-#    bl-help-pipemenu - an Openbox pipemenu for displaying help files
+#    al-help-pipemenu - an Openbox pipemenu for displaying help files
 #    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
 #
 #    This program is free software: you can redistribute it and/or modify
@@ -15,13 +15,15 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-HELP='    bl-help-pipemenu an Openbox Pipe Menu for displaying help files
+#	Renamed for ARCHLabs
+
+HELP='    al-help-pipemenu an Openbox Pipe Menu for displaying help files
     It should normally be called from an openbox menu.
 
 Options (usually passed from the menu):
     -h --help   show this message
 
-    If bl-help-pipemenu is called with no options (the usual method),
+    If al-help-pipemenu is called with no options (the usual method),
     it will output an xml openbox pipemenu displaying various help files,
     both online and on the system.
 '
@@ -36,28 +38,21 @@ do
     esac
 done
 
-BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
+BL_COMMON_LIBDIR='/usr/lib/archlabs/common'
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to source al-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
 menuStart
 menuSeparator 'Online Help'
 menuSeparator
-menuItem 'Forum Basic Help & Support' 'chromium "https://forums.bunsenlabs.org/viewforum.php?id=2"'
-menuItem 'Scripts, Tutorials & Tips' 'chromium "https://forums.bunsenlabs.org/viewforum.php?id=9"'
-menuSubmenu 'DebianWWW' 'Debian'
-menuItem 'Debian Documentation' 'chromium "https://www.debian.org/doc/"'
-menuItem 'Debian Handbook' 'chromium "https://debian-handbook.info/browse/jessie/"'
-menuItem 'Debian Reference' 'chromium "https://www.debian.org/doc/manuals/debian-reference/"'
-menuItem 'Wiki' 'chromium "https://wiki.debian.org/"'
-menuItem 'Forum' 'chromium "http://forums.debian.net/"'
-menuItem 'Package Search' 'chromium "https://www.debian.org/distrib/packages"'
-menuItem 'Package Tracker' 'chromium "https://tracker.debian.org/"'
-menuItem 'Security Tracker' 'chromium "https://security-tracker.debian.org/tracker/"'
-menuSubmenuEnd
+menuItem 'Forum Basic Help & Support' 'chromium "https://plus.google.com/u/0/communities/101475477052908495908"'
+menuItem 'Scripts, Tutorials & Tips' 'chromium "https://bbs.archlinux.org/viewforum.php?id=33"'
+
+menuSeparator
+
 menuItem 'Arch Wiki' 'chromium "https://wiki.archlinux.org/index.php/Table_of_contents"'
 
 menuSeparator
@@ -72,39 +67,43 @@ menuSubmenuEnd
 menuItem 'ArchWiki Openbox Guide' 'chromium "http://wiki.archlinux.org/index.php/Openbox"'
 menuItem 'Debian Wiki Openbox Guide' 'chromium "https://wiki.debian.org/Openbox"'
 menuItem 'Urukramas Openbox Guide' 'chromium "https://urukrama.wordpress.com/openbox-faq/"'
+menuItem 'Openbox Reddit' 'chromium "https://www.reddit.com/r/openbox/"'
 menuSubmenuEnd
 
 menuSubmenu 'Tint2WWW' 'Tint2'
 menuItem 'Tint2 Wiki: FAQ' 'chromium "https://gitlab.com/o9000/tint2/wikis/FAQ"'
 menuItem 'Tint2 Wiki: Configuration' 'chromium "https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md"'
 menuItem 'Tint2 Forum Thread' 'chromium "https://forums.bunsenlabs.org/viewtopic.php?id=254"'
-menuItem 'Tint2 man page' 'x-terminal-emulator -T "Tint2 man page" -e man tint2'
+menuItem 'Tint2 man page' 'termite -T "Tint2 man page" -e man tint2'
 menuSubmenuEnd
 
 menuSubmenu 'ConkyWWW' 'Conky'
 menuItem 'Conky Wiki' 'chromium "https://github.com/brndnmtthws/conky/wiki"'
 menuItem 'Conky Archive' 'chromium "http://crunchbang.org/forums/viewtopic.php?pid=371424"'
-menuItem 'Conky man pages' 'x-terminal-emulator -T "Conky man page" -e man conky'
+menuItem 'Conky man pages' 'termite -T "Conky man page" -e man conky'
 menuSubmenuEnd
 menuSeparator
 
 menuSubmenu 'ThemesWWW' 'Theme Resources'
 menuItem 'Bunsenlabs on DeviantArt' 'chromium "http://bunsenlabs.deviantart.com/"'
+menuItem 'Eye Candy Linux DeviantArt' 'chromium "http://eye-candy-linux.deviantart.com/"'
 menuItem 'Box-Look.org' 'chromium "http://www.box-look.org"'
 menuItem 'gnome-look.org' 'chromium "http://gnome-look.org/"'
+menuItem 'Eye Candy Linux Google+' 'chromium "https://plus.google.com/u/0/communities/104794997718869399105"'
+menuItem 'UnixPorn' 'chromium "https://www.reddit.com/r/unixporn/"'
+menuItem 'nixers.net' 'chromium "http://nixers.net/"'
 menuSubmenuEnd
-menuSeparator
+
 menuSeparator 'man pages'
-menuItem 'Compositor' 'x-terminal-emulator -T "Compositor man page" -e man compton'
-menuItem 'dmenu' 'x-terminal-emulator -T "dmenu man page" -e man dmenu'
-menuItem 'gmrun' 'x-terminal-emulator -T "gmrun man page" -e man gmrun'
-menuItem 'xrandr' 'x-terminal-emulator -T "xrandr man page" -e man xrandr'
+menuItem 'Compositor' 'termite -T "Compositor man page" -e man compton'
+menuItem 'dmenu' 'termite -T "dmenu man page" -e man dmenu'
+menuItem 'gmrun' 'termite -T "gmrun man page" -e man gmrun'
+menuItem 'xrandr' 'termite -T "xrandr man page" -e man xrandr'
 
 menuSeparator
-menuSubmenu 'BLhelp' 'Bunsen Help Files'
-menuItem 'How to Edit Menu' 'yad --button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="How to Edit the Menu" --filename="/usr/share/bunsen/docs/helpfile-menu.txt" --width=900 --height=700 --fontname=Monospace'
-menuItem 'About Bunsen Alternatives' 'yad --button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="About Bunsen Alternatives" --filename="/usr/share/bunsen/docs/helpfile-bl-alternatives.txt" --width=900 --height=700 --fontname=Monospace'
-menuItem 'Conkyzen Help' 'yad --button="OK":0 --center --window-icon=distributor-logo-bunsenlabs --text-info --title="Conkyzen Help" --filename="/usr/share/bunsen/docs/helpfile-conkyzen.txt" --width=900 --height=700 --fontname=Monospace'
+menuSubmenu 'ALhelp' 'ARCHLabs Help Files'
+menuItem 'How to Edit Menu' 'yad --button="OK":0 --center --window-icon=distributor-logo-archlabs --text-info --title="How to Edit the Menu" --filename="/usr/share/archlabs/docs/helpfile-menu.txt" --width=900 --height=700 --fontname=Monaco'
+menuItem 'Conkyzen Help' 'yad --button="OK":0 --center --window-icon=distributor-logo-archlabs --text-info --title="Conkyzen Help" --filename="/usr/share/archlabs/docs/helpfile-conkyzen.txt" --width=900 --height=700 --fontname=Monaco'
 menuSubmenuEnd
 
 menuEnd
diff --git a/installation/personal/settings/openbox/scripts/al-kb-pipemenu b/installation/personal/settings/openbox/scripts/al-kb-pipemenu
--- a/installation/personal/settings/openbox/scripts/al-kb-pipemenu
+++ b/installation/personal/settings/openbox/scripts/al-kb-pipemenu
@@ -1,5 +1,5 @@
 #!/bin/bash
-#    bl-kb-pipemenu - an Openbox pipemenu for displaying keybinds
+#    al-kb-pipemenu - an Openbox pipemenu for displaying keybinds
 #    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
 #
 #    This program is free software: you can redistribute it and/or modify
@@ -18,9 +18,11 @@
 # NB The keybinds in the menu are clickable, except for the Openbox
 # commands, which just exit the menu
 
-# bl-kb is used to parse rc.xml and send the output to a textfile
+# al-kb is used to parse rc.xml and send the output to a textfile
 
-HELP='    bl-kb-pipemenu an Openbox Pipe Menu for displaying keybinds
+#	Renamed for ARCHLabs
+
+HELP='    al-kb-pipemenu an Openbox Pipe Menu for displaying keybinds
     It should normally be called from an openbox menu.
 
 Options (usually passed from the menu):
@@ -30,11 +32,11 @@ Options (usually passed from the menu):
      commands, which just exit the menu.)
     --rcedit    backup and edit rc.xml
 
-If bl-keyboard-pipemenu is called with no options (the usual method),
+If al-keyboard-pipemenu is called with no options (the usual method),
 it will output an xml openbox pipemenu for displaying keybindings.
 
 NOTE: Some of the functionality of this pipemenu depends on the script
-/usr/bin/bl-kb which is provided by the package "bunsen-utilities".
+/usr/bin/al-kb which is provided by the package "archlabs-utilities".
 '
 # look for a help option somewhere
 for i in "$@"
@@ -47,21 +49,21 @@ do
     esac
 done
 
-BL_COMMON_LIBDIR="/usr/lib/bunsen/common"
+BL_COMMON_LIBDIR="/usr/lib/archlabs/common"
 USR_CFG_DIR="$HOME/.config/openbox"
-KBSCRIPT="bl-kb"
+KBSCRIPT="al-kb"
 RCPATH="$USR_CFG_DIR/rc.xml"
 KBTEXT="$USR_CFG_DIR/kbinds.txt"
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to locate al-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
-# test if bl-kb exists in path
+# test if al-kb exists in path
 if ! type "$KBSCRIPT" &> /dev/null;then
     menuStart
-    menuSeparator "$KBSCRIPT is not available. Try installing bunsen-utilities."
+    menuSeparator "$KBSCRIPT is not available. Try installing ARCHLabs-utilities."
     menuEnd
     exit 1
 fi
@@ -71,7 +73,7 @@ if [[ $1 = '--rcedit' ]];then # "Backup & Edit rc.xml" is chosen in menu
     NOW=$(date +"%Y%m%d-%H%M")
     RCBKP="$RCPATH.$NOW"
     cp "$RCPATH" "$RCBKP"
-    bl-text-editor "$RCPATH"        # open rc.xml in default editor
+    geany "$RCPATH"        # open rc.xml in default editor
     exit
 fi
 
diff --git a/installation/personal/settings/openbox/scripts/al-libreoffice-pipemenu b/installation/personal/settings/openbox/scripts/al-libreoffice-pipemenu
--- a/installation/personal/settings/openbox/scripts/al-libreoffice-pipemenu
+++ b/installation/personal/settings/openbox/scripts/al-libreoffice-pipemenu
@@ -1,5 +1,5 @@
 #!/bin/bash
-#    bl-libreoffice-pipemenu an Openbox Pipe Menu for use with LibreOffice
+#    al-libreoffice-pipemenu an Openbox Pipe Menu for use with LibreOffice
 #    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
 #    Copyright (C) 2013 Aleks-Daniel Jakimenko
 #    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
@@ -17,14 +17,14 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-HELP='    bl-libreoffice-pipemenu an Openbox Pipe Menu for use with LibreOffice
+HELP='    al-libreoffice-pipemenu an Openbox Pipe Menu for use with LibreOffice
     It should normally be called from an openbox menu.
 
 Options (usually passed from the menu):
     -h --help   show this message
     --install   install a part, or all, of the LibreOffice suite
 
-If bl-libreoffice-pipemenu is called with no options (the usual method),
+If al-libreoffice-pipemenu is called with no options (the usual method),
 it will output an xml openbox pipemenu
 for launching and installing LibreOffice components.
 '
@@ -39,10 +39,10 @@ do
     esac
 done
 
-BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
+BL_COMMON_LIBDIR='/usr/lib/archlabs/common'
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to locate al-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
diff --git a/installation/personal/settings/openbox/scripts/al-multimedia-pipemenu b/installation/personal/settings/openbox/scripts/al-multimedia-pipemenu
--- a/installation/personal/settings/openbox/scripts/al-multimedia-pipemenu
+++ b/installation/personal/settings/openbox/scripts/al-multimedia-pipemenu
@@ -1,5 +1,5 @@
 #!/bin/bash
-#    bl-multimedia-pipemenu - an Openbox pipemenu for Multimedia applications
+#    al-multimedia-pipemenu - an Openbox pipemenu for Multimedia applications
 #    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
 #    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
 #    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
@@ -20,7 +20,7 @@
 #   To change the entries shown in the Multimedia pipemenu:
 #   edit ".config/openbox/pipemenus.rc"
 
-HELP='    bl-multimedia-pipemenu an Openbox Pipe Menu for multimedia applications
+HELP='    al-multimedia-pipemenu an Openbox Pipe Menu for multimedia applications
     It should normally be called from an openbox menu.
 
 Options (usually passed from the menu):
@@ -28,7 +28,7 @@ Options (usually passed from the menu):
     --install   install a multimedia package
     (the package must be in the list defined in the pipemenu config file)
 
-    If bl-multimedia-pipemenu is called with no options (the usual method),
+    If al-multimedia-pipemenu is called with no options (the usual method),
     it will output an xml openbox pipemenu
     for launching and installing multimedia applications.
 
@@ -45,11 +45,11 @@ do
     esac
 done
 
-BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
+BL_COMMON_LIBDIR='/usr/lib/archlabs/common'
 USR_CFG_DIR="$HOME/.config/openbox"
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to source al-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 elif ! . "$USR_CFG_DIR/pipemenus.rc" 2> /dev/null; then
     echo $"Error: Failed to source pipemenus.rc in $USR_CFG_DIR" >&2
diff --git a/installation/personal/settings/openbox/scripts/al-tint2-pipemenu b/installation/personal/settings/openbox/scripts/al-tint2-pipemenu
--- a/installation/personal/settings/openbox/scripts/al-tint2-pipemenu
+++ b/installation/personal/settings/openbox/scripts/al-tint2-pipemenu
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-#    bl-tint2-pipemenu - an Openbox pipemenu for tint2 manipulation
-#    Copyright (C) 2015-2016 damo    <damo@bunsenlabs.org>
+#    al-tint2-pipemenu - an Openbox pipemenu for tint2 manipulation
+#    Copyright (C) 2015-2016 damo    <damo@archlabslabs.org>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -16,18 +16,18 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-HELP='    bl-tint2-pipemenu an Openbox Pipe Menu for tint2 manipulation
+HELP='    al-tint2-pipemenu an Openbox Pipe Menu for tint2 manipulation
     It should normally be called from an openbox menu.
 
 Options:
     -h --help   show this message
 
-    If bl-tint2-pipemenu is called with no options (the usual method),
+    If al-tint2-pipemenu is called with no options (the usual method),
     it will output an xml openbox pipemenu for handling tint2 sessions,
     and editing configuration files.
 
 For more information, see "man tint2"
-and "Help">"Tint2" in the BunsenLabs menu.
+and "Help">"Tint2" in the archlabsLabs menu.
 '
 # look for a help option somewhere
 for i in "$@"
@@ -40,20 +40,20 @@ do
     esac
 done
 
-BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
+BL_COMMON_LIBDIR='/usr/lib/archlabs/common'
 
 TINT2PATH="$HOME/.config/tint2"
 TINT2RC="$TINT2PATH/tint2rc"
-TZEN="bl-tint2zen"
+TZEN="al-tint2zen"
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to source al-include.cfg in $AL_COMMON_LIBDIR" >&2
     exit 1
 fi
 
 loadTEditmenu(){
     menuSeparator
-    menuItem "Default tint2rc" "bl-text-editor $TINT2RC"
+    menuItem "Default tint2rc" "geany $TINT2RC"
     if [ "$(pidof tint2)" ];then
         menuSubmenu "RunningTint2" "Running Tint2s"
         pgrep -a tint2 | while read -r pid cmd; do
@@ -64,7 +64,7 @@ loadTEditmenu(){
                     TINT="$TINT2RC"
                     TINT2="Default tint2rc"
                 fi
-                menuItem "$TINT2" "bl-text-editor $TINT"
+                menuItem "$TINT2" "geany $TINT"
             fi
         done
         menuSubmenuEnd
@@ -73,8 +73,8 @@ loadTEditmenu(){
 
 getTint2s(){
     menuSubmenu "EditTint2" "Edit Tint2s"
-        if type bl-tint2edit &>/dev/null;then  # bl-tint2edit script found
-            menuItem "Tint2 Editor" "bl-tint2edit"
+        if type al-tint2edit &>/dev/null;then  # al-tint2edit script found
+            menuItem "Tint2 Editor" "al-tint2edit"
             loadTEditmenu
         else
             loadTEditmenu
@@ -83,15 +83,15 @@ getTint2s(){
 }
 
 loadChoosermenu(){
-    if type $TZEN &>/dev/null;then  # bl-tint2zen script found
+    if type $TZEN &>/dev/null;then  # al-tint2zen script found
         menuItem "Tint2 Chooser" "$TZEN"
     fi
 }
 
 loadRestartmenu(){
     if [ "$(pidof tint2)" ];then
-        if type bl-tint2restart &>/dev/null;then  # bl-tint2restart script found
-            menuItem "Restart Tint2" "bl-tint2restart"
+        if type al-tint2restart &>/dev/null;then  # al-tint2restart script found
+            menuItem "Restart Tint2" "al-tint2restart"
         fi
     fi
 }
diff --git a/installation/personal/settings/openbox/scripts/al-x-www-browser-pipemenu b/installation/personal/settings/openbox/scripts/al-x-www-browser-pipemenu
--- a/installation/personal/settings/openbox/scripts/al-x-www-browser-pipemenu
+++ b/installation/personal/settings/openbox/scripts/al-x-www-browser-pipemenu
@@ -1,5 +1,5 @@
 #!/bin/bash
-#    bl-x-www-browser-pipemenu - an Openbox pipemenu for web browsers
+#    al-x-www-browser-pipemenu - an Openbox pipemenu for web browsers
 #    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
 #    Copyright (C) 2013 Aleks-Daniel Jakimenko
 #    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
@@ -21,7 +21,7 @@
 #   To change the entries shown in the Browsers pipemenu:
 #   edit ".config/openbox/pipemenus.rc"
 
-HELP='    bl-x-www-browser-pipemenu an Openbox Pipe Menu for web browsers
+HELP='    al-x-www-browser-pipemenu an Openbox Pipe Menu for web browsers
     It should normally be called from an openbox menu.
 
 Options (usually passed from the menu):
@@ -30,7 +30,7 @@ Options (usually passed from the menu):
     (the browser must be in the list defined in the pipemenu config file)
     (NOTE: Google Chrome will not appear in the menu on 32bit systems.)
 
-    If bl-x-www-browser-pipemenu is called with no options (the usual method),
+    If al-x-www-browser-pipemenu is called with no options (the usual method),
     it will output an xml openbox pipemenu
     for launching and installing web browsers.
 
@@ -47,16 +47,16 @@ do
     esac
 done
 
-BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
+BL_COMMON_LIBDIR='/usr/lib/archlabs/common'
 USR_CFG_DIR="$HOME/.config/openbox"
 
 KEY_URLS_GOOGLE=('https://dl-ssl.google.com/linux/linux_signing_key.pub')
 KEY_URLS_OPERA=('http://deb.opera.com/archive.key')
 
-declareDependencies wget
+#declareDependencies wget
 
-if ! . "$BL_COMMON_LIBDIR/bl-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source bl-include.cfg in $BL_COMMON_LIBDIR" >&2
+if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to source al-include.cfg in $BL_COMMON_LIBDIR" >&2
     exit 1
 elif ! . "$USR_CFG_DIR/pipemenus.rc" 2> /dev/null; then
     echo $"Error: Failed to source pipemenus.rc in $USR_CFG_DIR" >&2
@@ -109,7 +109,7 @@ addAptKey() {
 setupGoogleChromeStable() {
     addAptKey "${KEY_URLS_GOOGLE[@]}" || return 1
     say 'Creating APT sources file...' 1
-    echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee '/etc/apt/sources.list.d/google-chrome.list'
+    echo 'yaourt -S google-chrome' 
 }
 
 setupOpera() {
